---

- name: Exercicios
  hosts: all
  vars:
   seunome: douglas
  tasks:
   - name: "{{usuario}}"
     user:
      name: "{{item}}"
     with_items:
      - "{{seunome}}"
      - developer
      - devops

   - name: instalar pacotes
     package:
      name: 
       - htop
       - vim
       - cowsay
       - figlet

   - name: copiando arquivo para todas as maquinas
     file:
      path: /tmp/devops
      state: touch

   - name: colocando conteudo
     blockinfile:
      path: /tmp/devops
      block: |
        sou devops
        na 4linux

   - name: copiando arquivo para todas as maquinas
     file:
       path: /tmp/index
       state: touch
     when: ansible_hostname == "devops"

   - name: colocando conteudo
     blockinfile:
      path: /tmp/devops
      block: |
        sou devops
     when: ansible_hostname == "devops"
