- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "douglasdmiranda" }
    - {name: "user.email", value: "douglasdmiranda@gmail.com" }
    - {name: "ui.color", value: "True" }
