- name: instalando o Jenkins
  hosts: automation
  tasks:

   - name: install wget
     package:
      name: wget

   - name: Adicionando chave do repositorio
     shell: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"
   
   - name: Adicionando a Chave
     shell: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"
   - name: Install Jenkins
     package:
      name: jenkins
