- name: instalando o rundeck em centos
  hosts: automation
  tasks:
   - name: Instalando repositorio do rundeck
     yum:
      name: http://repo.rundeck.org/latest.rpm
      state: present

   - name: instalar o Java e o Rundeck
     package:
      name: "{{item}}"
     with_items:
        - java
        - rundeck
