- name: enviando para centos 
  copy:
   src: files/index.htm
   dest: /var/www/html/
  when: ansible_os_family == "RedHat"


- name: enviando para debian 
  copy:
   src: files/index.htm
   dest: /var/www/html
  when: ansible_os_family == "Debian"

