- name: instalando pacotes para debian
  package:
   name:
    - apache2
  when: ansible_os_family == "Debian"

- name: instalando pacotes para centos
  package:
   name:
    - httpd
  when: ansible_os_family == "RedHat"
